using System.Text;

internal static class GameListWriter
{
    internal static string BuildContent(IReadOnlyCollection<string> exes, string osFilter)
    {
        StringBuilder sb = new();
        sb.Append("# Discord detectable-games executable list.\n");
        sb.Append("# Regenerated by GameListUpdater. os=").Append(osFilter).Append(" games=").Append(exes.Count).Append('\n');
        foreach (string exe in exes) sb.Append(exe).Append('\n');
        return sb.ToString();
    }

    internal static void WriteAtomic(string path, string content)
    {
        string? directory = Path.GetDirectoryName(path);
        if (!string.IsNullOrEmpty(directory)) Directory.CreateDirectory(directory);

        string tmp = path + "." + Guid.NewGuid().ToString("N") + ".tmp";
        try
        {
            File.WriteAllText(tmp, content, new UTF8Encoding(false));

            if (OperatingSystem.IsWindows() && File.Exists(path))
            {
                // File.Replace is atomic on NTFS and preserves nothing we care about
                // here; the null third arg skips the backup copy.
                File.Replace(tmp, path, null);
            }
            else
            {
                // On Unix-like systems, renaming over an existing file on the same
                // filesystem is atomic. File.Move(..., overwrite: true) maps to that.
                File.Move(tmp, path, overwrite: true);
            }
        }
        catch
        {
            TryDelete(tmp);
            throw;
        }
    }

    internal static string NormalizeBody(string content)
    {
        StringBuilder sb = new();
        foreach (string line in content.Replace("\r", "").Split('\n'))
        {
            string t = line.Trim();
            if (t.Length == 0 || t[0] == '#') continue;
            sb.Append(t).Append('\n');
        }
        return sb.ToString();
    }

    internal static int CountBodyLines(string content)
    {
        int count = 0;
        foreach (string line in content.Replace("\r", "").Split('\n'))
        {
            string t = line.Trim();
            if (t.Length == 0 || t[0] == '#') continue;
            count++;
        }
        return count;
    }

    private static void TryDelete(string path)
    {
        try
        {
            if (File.Exists(path)) File.Delete(path);
        }
        catch
        {
            // Best-effort cleanup only; preserve the original write exception.
        }
    }
}
