<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <LangVersion>9.0</LangVersion>
    <Optimize>true</Optimize>
    <RootNamespace>GameListUpdater</RootNamespace>
    <AssemblyName>GameListUpdater</AssemblyName>
    <Company>Luc Duguay</Company>
    <Description>G915-Stutter-Fix game list updater (contributed by Timmaykc)</Description>
    <Copyright>MIT License</Copyright>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>
