using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Text;
using Newtonsoft.Json.Linq;

namespace GameListUpdater
{
    // Single-purpose, network-isolated companion to KeyboardRepeatFilter.exe.
    // Downloads Discord's public detectable-games database, extracts Windows
    // executable names, and writes games.txt next to this exe.
    //
    // Feature contributed by GitHub user Timmaykc (https://github.com/Timmaykc):
    // a manually-invoked game-list fetch that lets the tray app auto-switch to a
    // gaming profile while a detected game is running. Thank you.
    //
    // Exit codes (read by the tray app to choose which message to show):
    //   0 = list updated      1 = no update available      2 = error
    internal static class Program
    {
        private const string Url = "https://discord.com/api/v9/applications/detectable";

        // Generic runtime / dev hosts that appear in Discord's list but run many
        // non-game apps; excluded so they don't false-trigger the game profile.
        private static readonly HashSet<string> Denylist = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "dotnet.exe", "python.exe", "pythonw.exe", "node.exe",
            "ruby.exe", "perl.exe", "mono.exe", "pwsh.exe"
        };

        private static int Main()
        {
            // TLS 1.2 (Discord requires it). 12288 = Tls13, OR'd in numerically so
            // this still compiles if the enum member is absent on older targets.
            try
            {
                ServicePointManager.SecurityProtocol =
                    SecurityProtocolType.Tls12 | (SecurityProtocolType)12288;
            }
            catch
            {
                try { ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12; }
                catch { }
            }

            try
            {
                string json = Download(Url);
                var exes = ExtractWin32Exes(json);
                if (exes.Count == 0)
                {
                    Console.Error.WriteLine("ERROR no executables parsed from response");
                    return 2;
                }

                var sorted = new List<string>(exes);
                sorted.Sort(StringComparer.Ordinal);

                var sb = new StringBuilder();
                sb.Append("# Discord detectable-games executable list.\n");
                sb.Append("# Regenerated by GameListUpdater.exe. games=").Append(sorted.Count).Append('\n');
                foreach (var e in sorted) sb.Append(e).Append('\n');
                string newContent = sb.ToString();

                string path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "games.txt");
                string oldContent = File.Exists(path) ? File.ReadAllText(path) : null;

                if (oldContent != null && NormalizeBody(oldContent) == NormalizeBody(newContent))
                {
                    Console.WriteLine("NO_UPDATE games=" + sorted.Count);
                    return 1;
                }

                WriteAtomic(path, newContent);
                Console.WriteLine("UPDATED games=" + sorted.Count);
                return 0;
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine("ERROR " + ex.Message);
                return 2;
            }
        }

        // Write via a temp file then swap into place, so a crash or a concurrent
        // read by the tray app can never see a half-written games.txt (a truncated
        // list would silently break game detection). BOM-less UTF-8: the tray app
        // reads this back line by line.
        private static void WriteAtomic(string path, string content)
        {
            string tmp = path + ".tmp";
            File.WriteAllText(tmp, content, new UTF8Encoding(false));
            if (File.Exists(path))
            {
                // File.Replace is atomic on NTFS and preserves nothing we care about
                // here; the null third arg skips the backup copy.
                File.Replace(tmp, path, null);
            }
            else
            {
                File.Move(tmp, path);
            }
        }

        // Compare only the executable lines so a changed header count never
        // produces a false "updated" result.
        private static string NormalizeBody(string content)
        {
            var sb = new StringBuilder();
            foreach (var line in content.Replace("\r", "").Split('\n'))
            {
                var t = line.Trim();
                if (t.Length == 0 || t[0] == '#') continue;
                sb.Append(t).Append('\n');
            }
            return sb.ToString();
        }

        private static string Download(string url)
        {
            var req = (HttpWebRequest)WebRequest.Create(url);
            req.UserAgent = "G915-Stutter-Fix-GameListUpdater/1.0 (+https://github.com/lucduguaysita/G915-Stutter-Fix)";
            req.Accept = "application/json";
            // The detectable list is ~1MB+ of JSON; let the server compress it.
            req.AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate;
            req.Timeout = 45000;
            req.ReadWriteTimeout = 45000;
            using (var resp = (HttpWebResponse)req.GetResponse())
            using (var s = resp.GetResponseStream())
            using (var r = new StreamReader(s, Encoding.UTF8))
            {
                return r.ReadToEnd();
            }
        }

        private static HashSet<string> ExtractWin32Exes(string json)
        {
            var result = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var arr = JArray.Parse(json);
            foreach (var game in arr)
            {
                var execs = game["executables"] as JArray;
                if (execs == null) continue;
                foreach (var ex in execs)
                {
                    var os = (string)ex["os"];
                    var name = (string)ex["name"];
                    if (os != "win32" || string.IsNullOrEmpty(name)) continue;

                    // Reduce to the bare filename (entries may include path segments).
                    name = name.Replace('\\', '/');
                    int slash = name.LastIndexOf('/');
                    if (slash >= 0) name = name.Substring(slash + 1);
                    name = name.Trim();
                    if (name.Length > 0 && !Denylist.Contains(name)) result.Add(name);
                }
            }
            return result;
        }
    }
}
