using System.Text;

namespace G915Fix.Core.Games;

/// <summary>Stores a game list in the portable line-based games.txt format.</summary>
public sealed class FileGameListStore : IGameListStore
{
    private readonly string _path;
    private readonly GameListPlatform _platform;

    public FileGameListStore(string path, GameListPlatform platform)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(path);
        _path = Path.GetFullPath(path);
        _platform = platform;
    }

    public async Task<IReadOnlySet<string>> LoadAsync(CancellationToken cancellationToken = default)
    {
        var games = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        if (!File.Exists(_path))
        {
            return games;
        }

        using var reader = new StreamReader(_path);
        while (await reader.ReadLineAsync(cancellationToken).ConfigureAwait(false) is string line)
        {
            string name = line.Trim();
            if (name.Length > 0 && name[0] != '#')
            {
                games.Add(name);
            }
        }

        return games;
    }

    public Task SaveAsync(IReadOnlySet<string> executableNames, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(executableNames);
        cancellationToken.ThrowIfCancellationRequested();

        string[] names = executableNames.OrderBy(name => name, StringComparer.Ordinal).ToArray();
        string content = string.Join('\n',
            [
                "# Discord detectable-games executable list.",
                $"# Regenerated by G915Fix. os={GameListUpdateOptions.ToDiscordOsFilter(_platform)} games={names.Length}",
                .. names,
                string.Empty
            ]);
        return WriteAtomicAsync(_path, content, cancellationToken);
    }

    private static async Task WriteAtomicAsync(string path, string content, CancellationToken cancellationToken)
    {
        string? directory = Path.GetDirectoryName(path);
        if (!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }

        string temporaryPath = path + "." + Guid.NewGuid().ToString("N") + ".tmp";
        try
        {
            await File.WriteAllTextAsync(temporaryPath, content, new UTF8Encoding(false), cancellationToken)
                .ConfigureAwait(false);
            File.Move(temporaryPath, path, overwrite: true);
        }
        finally
        {
            try
            {
                if (File.Exists(temporaryPath))
                {
                    File.Delete(temporaryPath);
                }
            }
            catch
            {
                // The successful write is more important than best-effort cleanup.
            }
        }
    }
}
